### ISSUE TITLE
BUG: When adding coins into the portfolio state, add the balance key as well. Also prevent saving a Coin if balance is 0.

### ISSUE THREAD

**Issue by leongaban** [Futuratum/moon.holdings#19]
- [x] After saving a coin, be sure to include the balance key into the portfolio coin.
- [x] If balance is 0 in the `SquareEdit` component, then disable the save button.

![screen shot 2018-03-16 at 3 24 00 pm](https://user-images.githubusercontent.com/191636/37543017-3e8f4ae2-292e-11e8-89f5-51ef98c69e8c.png)

**Comment by leon-yum** [comment]
Fixed and merged: https://github.com/Futuratum/moon.holdings/pull/25
