### ISSUE TITLE
Add a basic line chart.

### ISSUE THREAD

**Issue by leongaban** [Futuratum/moon.holdings#52]
http://recharts.org/en-US/

The Chart will display a simple price line. Which follows the aggregate value of the user's total portfolio over a timeframe. 1H, 1D (24hrs), 1W, 1M

![screen shot 2018-07-09 at 4 07 30 pm](https://user-images.githubusercontent.com/191636/42476090-5b99c90a-8392-11e8-92df-a58a7f911de1.png)

**Comment by prochafilho** [comment]
Hmm, it does not seem that [Coincap](https://coinmarketcap.com/api/) has an usuable api for prices, any suggestions?

**Comment by leongaban** [comment]
Oh start with coinmarketcap.com’s api

**Comment by leongaban** [comment]
services/api has the call

**Comment by prochafilho** [comment]
That api does not give us access to historic data

**Comment by leongaban** [comment]
Hmm wondering if we may have to use this then: https://www.cryptocompare.com/api/#introduction

**Comment by prochafilho** [comment]
Let me review them and I will let you know what could be the best option

**Comment by leongaban** [comment]
Awesome man, that would be great! Yeah it doesn't have to be a fancy chart
at all... literally I think simplicity is key here. Just a curved line,
with no axis even, just to show the state of the price movement in the last
24hours / 7 days if possible.

**Comment by tmlee** [comment]
If you guys are looking for price API with historical data as well, may i invite you to try ours at https://www.coingecko.com/api/docs/v3

would like to hear your thoughts and suggestions

**Comment by leongaban** [comment]
@tmlee Thanks for the suggestion! We decided to go with Nomics.
@prochafilho Dude we can do real candle stick data with Nomics!

Aggregated OHLCV Candles http://docs.nomics.com/#operation/getCandles

**Comment by tmlee** [comment]
No problem @leongaban i am here should you decide to use any of our other endpoints at some point in the future

**Comment by leongaban** [comment]
I'm going to close this issue, we will re-visit charting once we start on the Moonholdings.io version.
