### ISSUE TITLE
Get rid of WARNING in asset size limit error (won't build)

### ISSUE THREAD

**Issue by leongaban** [Futuratum/moon.holdings#95]
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  index_bundle.js (519 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (519 KiB)
      index_bundle.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

**Comment by leongaban** [comment]
@astericky @prochafilho could one of you guys take this? currently in the `dev` branch. I can no longer run `yarn start`.

**Comment by leongaban** [comment]
Stackoverflow question posted: https://stackoverflow.com/questions/52723381/webpack-size-exceeds-the-recommended-limit-244-kib

**Comment by prochafilho** [comment]
`dev` branch is gone.

**Comment by prochafilho** [comment]
`dev` branch has been deleted
